site_name: Tutorial For UESTC3036
site_url: https://zhangjiayuan.me/tutorial_UESTC3036/
use_directory_urls: true

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
          nav:
            - Home: index.md
            - Python and Jupyter Notebook Installation Guide: Python and Jupyter Notebook 安装指南.md
            - Anaconda and VSCode Installation Guide: Optional.md
            - Extra Resources: Extra.md
        - locale: zh
          name: 中文
          build: true
          nav:
            - 首页: index.md
            - Python and Jupyter Notebook 安装指南: Python and Jupyter Notebook 安装指南.md
            - Anaconda and VSCode 安装指南: Optional.md
            - 额外资源: Extra.md